server:
  error:
    include-stacktrace: on_trace_param
remitly:
  shortly:
    expiration-days: 14
    db-cleanup-cron: 0 0 12 * * ? # every day at 12pm
    cache-eviction-cron: 0 0 0/2 * * ? #every 2 hours
spring:
  cache:
    cache-names: urls
  profiles:
    active: dev,default
---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb+srv://test:test@cluster0-7rakj.mongodb.net/test?retryWrites=true&w=majority
      database: shortly
---
spring:
  profiles: in-memory-db

---
spring:
  profiles: cloud