server:
  error:
    include-stacktrace: on_trace_param
remitly:
  shortly:
    expiration-days: 14
spring:
  cache:
    cache-names: urls
  profiles:
    active: dev,default
---
spring:
  profiles: dev
  data:
    mongodb:
      uri: mongodb+srv://test:<pass>@cluster0-7rakj.mongodb.net/test?retryWrites=true&w=majority
      database: shortly
---
spring:
  profiles: in-memory-db

---
spring:
  profiles: cloud